name: CMake Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set build variables
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Install Dependencies
      run: >
        sudo apt-get install -y 
        libxrandr-dev
        libxinerama-dev
        libxcursor-dev
        libxi-dev
        libxkbcommon-dev
        libgl-dev
        libglu1-mesa-dev
        libgles2-mesa-dev
        libegl1-mesa-dev
        mesa-utils

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=clang++
        -DCMAKE_C_COMPILER=clang
        -DCMAKE_BUILD_TYPE=Release
        -S ${{ github.workspace }}

    - name: Build Project
      run: >
        cmake
        --build ${{ steps.strings.outputs.build-output-dir }}
        --config Release
        --parallel 4

